package hardening

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"

	utils "github.com/louiseschmidtgen/k8s-hardening/internal"
)

const systemConfFileHeader = "# AUTOGENERATED - DO NOT EDIT\n# Generated by the k8s snap for system tuning required for kubelet to work in DISA-STIG hardened environment.\n"

var (
	reK8sDISAConfFile = regexp.MustCompile(`^(\d+)-k8s-stig.conf$`)
	reConfFiles       = regexp.MustCompile(`^(\d+)-.*\.conf$`)
)

func ApplyFix(baseline, tailoringFile, nodeRole string) error {
	// 1. Load config (merge baseline and tailoringFile)
	config, err := LoadConfig(baseline, tailoringFile)
	if err != nil {
		return err
	}

	// 3. Install usg and apply disa_stig if requested
	if config.USG.Apply != nil && *config.USG.Apply {
		if err := installUSG(); err != nil {
			return err
		}
		if err := applyUSGProfile(baseline); err != nil {
			return err
		}
	}

	// 2. Create UFW rules (firewall)
	if config.UFW.Apply != nil && *config.UFW.Apply {
		if err := createUFWRules(); err != nil {
			return err
		}
	}

	// 4. Remove sshd if worker node and requested
	if nodeRole == "worker" && *config.SSHDRemoval.Apply {
		if err := removeSSHD(); err != nil {
			return err
		}
	}

	// 5. Write audit-policy.yaml if requested
	if *config.AuditLogging.Apply {
		if err := writeAuditPolicy(config.AuditLogging.AuditPolicyPath, config.AuditLogging.AuditPolicyName); err != nil {
			return err
		}
	}

	// 6. Write sysctl config for system tuning if requested
	if *config.SystemTuning.Apply {
		if err := ensureSystemTuningConfigFile(config.SystemTuning.SystemParameters); err != nil {
			return err
		}
		if err := applySysctl(); err != nil {
			return err
		}
	}

	return nil
}

func installUSG() error {
	fmt.Println("Checking if USG is installed...")
	checkCmd := exec.Command("which", "usg")
	if err := checkCmd.Run(); err == nil {
		fmt.Println("USG is already installed.")
		return nil
	}

	fmt.Println("Installing USG (Uncomplicated Security Guidelines)...")
	installCmd := exec.Command("sudo", "apt-get", "install", "-y", "usg")
	if err := installCmd.Run(); err != nil {
		return err
	}
	return nil
}

func applyUSGProfile(profile string) error {
	fmt.Printf("Applying USG profile: %s...\n", profile)

	fixCmd := exec.Command("sudo", "usg", "fix", profile)
	out, err := fixCmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("Error applying USG profile: %v\nOutput: %s", err, out)
	}
	return nil
}

func removeSSHD() error {
	fmt.Println("Removing SSHD (OpenSSH Server) if present...")
	removeCmd := exec.Command("sudo", "apt-get", "remove", "-y", "openssh-server")
	if err := removeCmd.Run(); err != nil {
		return fmt.Errorf("Error removing OpenSSH Server: %v", err)
	}
	return nil
}

func writeAuditPolicy(path, name *string) error {
	if path == nil || name == nil {
		return fmt.Errorf("Invalid audit policy path or name")
	}

	auditPolicyPath := filepath.Join(*path, *name)
	auditPolicy := `
# Log all requests at the Metadata level.
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: Metadata
`

	if err := utils.WriteFile(auditPolicyPath, []byte(auditPolicy), os.FileMode(0o644)); err != nil {
		return fmt.Errorf("Error writing audit policy: %v", err)
	}
	return nil
}

func createUFWRules() error {
	fmt.Println("Creating UFW (Uncomplicated Firewall) rules...")

	// 3. Allow Kubernetes service ports
	// TODO: make configurable
	ports := []string{
		"6443/tcp", "10250/tcp", "10257/tcp", "10259/tcp", "2379/tcp", "2380/tcp", "6400/tcp", "4240/tcp", "8472/udp",
	}
	for _, port := range ports {
		if err := exec.Command("sudo", "ufw", "allow", port).Run(); err != nil {
			return fmt.Errorf("failed to allow port %s: %w", port, err)
		}
	}

	fmt.Println("UFW rules applied for Canonical Kubernetes.")
	return nil
}

// ensureSystemTuningConfigFile checks for a k8s system configuration tuning
// and creates one at the highest order if the file does not exist yet.
func ensureSystemTuningConfigFile(systemParameters map[string]*string) error {
	confPath, err := utils.GetFileMatches("/etc/sysctl.d", reK8sDISAConfFile)
	if err != nil {
		return fmt.Errorf("failed to check for existing system tuning file: %w", err)
	}

	if len(confPath) != 0 {
		return nil
	}

	maxOrder, err := GetHighestConfigFileOrder("/etc/sysctl.d", reConfFiles)
	if err != nil {
		return fmt.Errorf("failed to check for highest order system tuning file: %w", err)
	}

	newFile := filepath.Join("/etc/sysctl.d", fmt.Sprintf("%d-k8s.conf", maxOrder+1))
	data := []byte(systemConfFileHeader)
	for param, value := range systemParameters {
		if value != nil {
			data = append(data, []byte(fmt.Sprintf("%s=%s\n", param, *value))...)
		}
	}

	// iterate over system params

	if err = utils.WriteFile(newFile, data, 0o600); err != nil {
		return fmt.Errorf("failed to create system tuning file: %w", err)
	}
	return nil
}

// GetHighestConfigFileOrder returns the path of the file in a dir matching a file like 10-xyz.conf
// using the regex `^(\d+)-.*\.conf$` or returns 0s if no match was found.
func GetHighestConfigFileOrder(path string, reConfFiles *regexp.Regexp) (int, error) {
	maxOrder := 0
	entries, err := os.ReadDir(path)
	if err != nil {
		return maxOrder, err
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		matches := reConfFiles.FindStringSubmatch(entry.Name())
		if matches == nil {
			continue
		}

		// Check for configuration file order number
		numStr := matches[1]
		num, err := strconv.Atoi(numStr)
		if err != nil {
			continue
		}
		if num > maxOrder {
			maxOrder = num
		}
	}

	return maxOrder, nil
}

func applySysctl() error {
	fmt.Println("Applying sysctl settings...")

	applyCmd := exec.Command("sudo", "sysctl", "--system")
	if err := applyCmd.Run(); err != nil {
		return fmt.Errorf("failed to apply sysctl settings: %w", err)
	}
	return nil
}
