package hardening

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"

	utils "github.com/louiseschmidtgen/k8s-hardening/internal"
)

const systemConfFileHeader = "# AUTOGENERATED - DO NOT EDIT\n# Generated by the k8s snap for system tuning required for kubelet to work in DISA-STIG hardened environment.\n"

var (
	reK8sDISAConfFile = regexp.MustCompile(`^(\d+)-k8s-stig.conf$`)
	reConfFiles       = regexp.MustCompile(`^(\d+)-.*\.conf$`)
)

func ApplyFix(baseline, tailoringFile, nodeRole string) error {
	// 1. Load config (merge baseline and tailoringFile)
	config, err := LoadConfig(baseline, tailoringFile)
	if err != nil {
		return err
	}

	// 2. Install usg and apply disa_stig if requested
	if config.USG.Apply != nil && *config.USG.Apply {
		if err := applyUSGProfile(); err != nil {
			return err
		}
	}

	// 3. Create UFW rules (firewall)
	if config.UFW.Apply != nil && *config.UFW.Apply {
		if err := createUFWRules(nodeRole); err != nil {
			return err
		}
	}

	// 4. Remove sshd if worker node and requested
	if nodeRole == "worker" && *config.SSHDRemoval.Apply {
		if err := removeSSHD(); err != nil {
			return err
		}
	}

	// 5. Write audit-policy.yaml if requested
	if *config.AuditLogging.Apply {
		if err := writeAuditPolicy(config.AuditLogging.AuditPolicyPath, config.AuditLogging.AuditPolicyName); err != nil {
			return err
		}
	}

	// 6. Write sysctl config for system tuning if requested
	if *config.SystemTuning.Apply {
		if err := ensureSystemTuningConfigFile(config.SystemTuning.SystemParameters); err != nil {
			return err
		}
		if err := applySysctl(); err != nil {
			return err
		}
	}

	return nil
}

func applyUSGProfile() error {
	fmt.Println("Running USG host compliance script...")
	scriptPath := "internal/disa-stig/02-usg.sh"
	cmd := exec.Command("sudo", "bash", scriptPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("Error running USG script: %v", err)
	}
	return nil
}

func removeSSHD() error {
	fmt.Println("Removing SSHD (OpenSSH Server) if present...")
	scriptPath := "internal/disa-stig/04-remove-sshd.sh"
	cmd := exec.Command("sudo", "bash", scriptPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("Error removing OpenSSH Server: %v", err)
	}
	return nil
}

func writeAuditPolicy(path, name *string) error {
	fmt.Println("Writing audit-policy.yaml for kube-apiserver...")
	if path == nil || name == nil {
		return fmt.Errorf("Invalid audit policy path or name")
	}
	scriptPath := "internal/disa-stig/05-audit-policy.sh"
	cmd := exec.Command("sudo", "bash", scriptPath, *path, *name)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("Error writing audit policy: %v", err)
	}
	return nil
}

func createUFWRules(nodeRole string) error {
	fmt.Println("Creating UFW (Uncomplicated Firewall) rules...")

	scriptPath := fmt.Sprintf("internal/disa-stig/03-ufw-%s.sh", nodeRole)
	cmd := exec.Command("sudo", "bash", scriptPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("Error creating UFW rules: %v", err)
	}

	fmt.Println("UFW rules applied for Canonical Kubernetes.")
	return nil
}

// ensureSystemTuningConfigFile checks for a k8s system configuration tuning
// and creates one at the highest order if the file does not exist yet.
func ensureSystemTuningConfigFile(systemParameters map[string]*string) error {
	confPath, err := utils.GetFileMatches("/etc/sysctl.d", reK8sDISAConfFile)
	if err != nil {
		return fmt.Errorf("failed to check for existing system tuning file: %w", err)
	}

	if len(confPath) != 0 {
		return nil
	}

	maxOrder, err := GetHighestConfigFileOrder("/etc/sysctl.d", reConfFiles)
	if err != nil {
		return fmt.Errorf("failed to check for highest order system tuning file: %w", err)
	}

	newFile := filepath.Join("/etc/sysctl.d", fmt.Sprintf("%d-k8s-stig.conf", maxOrder+1))
	data := []byte(systemConfFileHeader)
	for param, value := range systemParameters {
		if value != nil {
			data = append(data, []byte(fmt.Sprintf("%s=%s\n", param, *value))...)
		}
	}

	// iterate over system params

	if err = utils.WriteFile(newFile, data, 0o600); err != nil {
		return fmt.Errorf("failed to create system tuning file: %w", err)
	}
	return nil
}

// GetHighestConfigFileOrder returns the path of the file in a dir matching a file like 10-xyz.conf
// using the regex `^(\d+)-.*\.conf$` or returns 0s if no match was found.
func GetHighestConfigFileOrder(path string, reConfFiles *regexp.Regexp) (int, error) {
	maxOrder := 0
	entries, err := os.ReadDir(path)
	if err != nil {
		return maxOrder, err
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		matches := reConfFiles.FindStringSubmatch(entry.Name())
		if matches == nil {
			continue
		}

		// Check for configuration file order number
		numStr := matches[1]
		num, err := strconv.Atoi(numStr)
		if err != nil {
			continue
		}
		if num > maxOrder {
			maxOrder = num
		}
	}

	return maxOrder, nil
}

func applySysctl() error {
	fmt.Println("Applying sysctl settings...")

	applyCmd := exec.Command("sudo", "sysctl", "--system")
	if err := applyCmd.Run(); err != nil {
		return fmt.Errorf("failed to apply sysctl settings: %w", err)
	}
	return nil
}
