#!/bin/bash
set -euo pipefail

# Usage: sudo bash 06-system-tuning.sh <param1>=<value1> <param2>=<value2> ...
SYSCTL_DIR="/etc/sysctl.d"
HEADER="# AUTOGENERATED - DO NOT EDIT\n# Generated by the k8s snap for system tuning required for kubelet to work in DISA-STIG hardened environment.\n"

# Find existing k8s-stig config file
conf_path=$(find "$SYSCTL_DIR" -maxdepth 1 -type f -regex ".*/[0-9]+-k8s-stig\\.conf" || true)
if [ -n "$conf_path" ]; then
	echo "System tuning file already exists: $conf_path"
	exit 0
fi

# Find highest order number among .conf files
max_order=0
for f in "$SYSCTL_DIR"/*.conf; do
	fname=$(basename "$f")
	if [[ "$fname" =~ ^([0-9]+)-.*\.conf$ ]]; then
		num=${BASH_REMATCH[1]}
		if (( num > max_order )); then
			max_order=$num
		fi
	fi
done

new_file="$SYSCTL_DIR/$((max_order+1))-k8s-stig.conf"
echo -e "$HEADER" | sudo tee "$new_file" > /dev/null

for param in "$@"; do
	if [[ "$param" =~ ^([^=]+)=(.+)$ ]]; then
		key="${BASH_REMATCH[1]}"
		value="${BASH_REMATCH[2]}"
		echo "$key=$value" | sudo tee -a "$new_file" > /dev/null
	fi
done

sudo chmod 600 "$new_file"
echo "Created system tuning file: $new_file"
